repos:
- repo: local
  hooks:
  - id: winipedia-utils
    name: winipedia-utils
    entry: python -m winipedia_utils.git.pre_commit.run_hooks
    language: system
    always_run: true
    pass_filenames: false
