name: Health Check Workflow
'on':
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  schedule:
  - cron: 0 6 * * *
  workflow_dispatch: {}
permissions: {}
run-name: Health Check Workflow
defaults:
  run:
    shell: bash
jobs:
  health_check_matrix:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python-version:
        - '3.12'
        - '3.13'
        - '3.14'
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Setup Git
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Poetry
      uses: snok/install-poetry@main
    - name: Install Dependencies
      run: poetry install
    - name: Setup CI keyring
      run: poetry run pip install keyrings.alt && poetry run python -c "import keyring;
        from keyrings.alt.file import PlaintextKeyring; keyring.set_keyring(PlaintextKeyring());"
    - name: Protect Repository
      run: poetry run python -m winipedia_utils.git.github.repo.protect
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: Run Hooks
      run: poetry run pre-commit run --all-files --verbose
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  health_check:
    runs-on: ubuntu-latest
    needs:
    - health_check_matrix
    steps:
    - name: Aggregate Matrix Results
      run: echo 'Aggregating matrix results into one job.'
