name: Health Check Workflow
'on':
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  schedule:
  - cron: 0 5 * * 1
  workflow_dispatch: {}
permissions:
  contents: read
run-name: Health Check Workflow
jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: 3.x
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Extract Version from pyproject.toml
      id: version
      run: 'version=$(poetry version -s) && echo "Project version: $version" && echo
        "version=v$version" >> $GITHUB_OUTPUT'
    - name: Install Dependencies
      run: poetry install
    - name: Run Hooks
      run: poetry run pre-commit run --all-files --verbose
