name: Release Workflow
'on':
  workflow_dispatch: {}
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  schedule:
  - cron: 0 6 * * 2
  push:
    branches:
    - main
permissions:
  contents: write
run-name: Release Workflow
defaults:
  run:
    shell: bash
jobs:
  health_check_matrix:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python-version:
        - '3.12'
        - '3.13'
        - '3.14'
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout_repository
      id: checkout_repository
      uses: actions/checkout@main
    - name: setup_python
      id: setup_python
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup_poetry
      id: setup_poetry
      uses: snok/install-poetry@main
    - name: add_poetry_to_windows_path
      id: add_poetry_to_windows_path
      run: echo 'C:/Users/runneradmin/.local/bin' >> $GITHUB_PATH
      if: runners.os == 'Windows'
    - name: install_python_dependencies
      id: install_python_dependencies
      run: poetry install
    - name: setup_keyring
      id: setup_keyring
      run: poetry run pip install keyrings.alt && poetry run python -c "import keyring;
        from keyrings.alt.file import PlaintextKeyring; keyring.set_keyring(PlaintextKeyring());"
    - name: protect_repository
      id: protect_repository
      run: poetry run python -m winipedia_utils.git.github.repo.protect
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: run_pre_commit_hooks
      id: run_pre_commit_hooks
      run: poetry run pre-commit run --all-files --verbose
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  health_check:
    needs:
    - health_check_matrix
    runs-on: ubuntu-latest
    steps:
    - name: aggregate_matrix_results
      id: aggregate_matrix_results
      run: echo 'Aggregating matrix results into one job.'
  build:
    needs:
    - health_check
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
      fail-fast: true
    runs-on: ${{ matrix.os }}
    if: ' -f winipedia_utils/build/build.py'
    steps:
    - name: checkout_repository
      id: checkout_repository
      uses: actions/checkout@main
    - name: setup_python
      id: setup_python
      uses: actions/setup-python@main
    - name: setup_poetry
      id: setup_poetry
      uses: snok/install-poetry@main
    - name: add_poetry_to_windows_path
      id: add_poetry_to_windows_path
      run: echo 'C:/Users/runneradmin/.local/bin' >> $GITHUB_PATH
      if: runners.os == 'Windows'
    - name: install_python_dependencies
      id: install_python_dependencies
      run: poetry install
    - name: build_artifacts
      id: build_artifacts
      run: poetry run python -m winipedia_utils.build.build
    - name: create_folder
      id: create_folder
      run: mkdir artifacts
    - name: build_artifacts
      id: build_artifacts
      run: poetry run python -m winipedia_utils.build.build
    - name: upload_artifacts
      id: upload_artifacts
      uses: actions/upload-artifact@main
      with:
        name: winipedia_utils-${{ runner.os }}
        path: artifacts
  release:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - name: checkout_repository
      id: checkout_repository
      uses: actions/checkout@main
    - name: setup_python
      id: setup_python
      uses: actions/setup-python@main
    - name: setup_poetry
      id: setup_poetry
      uses: snok/install-poetry@main
    - name: add_poetry_to_windows_path
      id: add_poetry_to_windows_path
      run: echo 'C:/Users/runneradmin/.local/bin' >> $GITHUB_PATH
      if: runners.os == 'Windows'
    - name: install_python_dependencies
      id: install_python_dependencies
      run: poetry install
    - name: setup_git
      id: setup_git
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: setup_keyring
      id: setup_keyring
      run: poetry run pip install keyrings.alt && poetry run python -c "import keyring;
        from keyrings.alt.file import PlaintextKeyring; keyring.set_keyring(PlaintextKeyring());"
    - name: run_pre_commit_hooks
      id: run_pre_commit_hooks
      run: poetry run pre-commit run --all-files --verbose
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: commit_added_changes
      id: commit_added_changes
      run: 'git commit --no-verify -m ''[skip ci] CI/CD: Committing possible added
        changes (e.g.: pyproject.toml and poetry.lock)'''
    - name: push_commits
      id: push_commits
      run: git push
    - name: create_and_push_tag
      id: create_and_push_tag
      run: git tag v$(poetry version -s) && git push origin v$(poetry version -s)
    - name: download_artifacts
      id: download_artifacts
      uses: actions/download-artifact@main
      with:
        path: artifacts
    - name: build_changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@develop
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: create_release
      id: create_release
      uses: ncipollo/release-action@main
      with:
        tag: v$(poetry version -s)
        name: ${{ github.event.repository.name }} v$(poetry version -s)
        body: ${ steps.build_changelog.outputs.changelog }
        artifacts: artifacts*
