name: Release Workflow
'on':
  workflow_dispatch: {}
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  schedule:
  - cron: 0 6 * * 2
  push:
    branches:
    - main
permissions:
  contents: write
run-name: Release Workflow
defaults:
  run:
    shell: bash
jobs:
  health_check_matrix:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python-version:
        - '3.12'
        - '3.13'
        - '3.14'
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@main
    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Poetry
      id: setup_poetry
      uses: snok/install-poetry@main
    - name: Add Poetry To Windows Path
      id: add_poetry_to_windows_path
      run: echo 'C:/Users/runneradmin/.local/bin' >> $GITHUB_PATH
      if: ${{ runner.os }} == 'Windows'
    - name: Install Python Dependencies
      id: install_python_dependencies
      run: poetry install
    - name: Setup Keyring
      id: setup_keyring
      run: poetry run pip install keyrings.alt && poetry run python -c "import keyring;
        from keyrings.alt.file import PlaintextKeyring; keyring.set_keyring(PlaintextKeyring());"
    - name: Protect Repository
      id: protect_repository
      run: poetry run python -m winipedia_utils.git.github.repo.protect
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: Run Pre Commit Hooks
      id: run_pre_commit_hooks
      run: poetry run pre-commit run --all-files --verbose
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  health_check:
    needs:
    - health_check_matrix
    runs-on: ubuntu-latest
    steps:
    - name: Aggregate Matrix Results
      id: aggregate_matrix_results
      run: echo 'Aggregating matrix results into one job.'
  build:
    needs:
    - health_check
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@main
    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@main
    - name: Setup Poetry
      id: setup_poetry
      uses: snok/install-poetry@main
    - name: Add Poetry To Windows Path
      id: add_poetry_to_windows_path
      run: echo 'C:/Users/runneradmin/.local/bin' >> $GITHUB_PATH
      if: ${{ runner.os }} == 'Windows'
    - name: Install Python Dependencies
      id: install_python_dependencies
      run: poetry install
    - name: Create Folder
      id: create_folder
      run: mkdir artifacts
    - name: Build Artifacts
      id: build_artifacts
      run: poetry run python -m winipedia_utils.build.build
    - name: Upload Artifacts
      id: upload_artifacts
      uses: actions/upload-artifact@main
      with:
        name: winipedia_utils-${{ runner.os }}
        path: artifacts
  release:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@main
    - name: Setup Python
      id: setup_python
      uses: actions/setup-python@main
    - name: Setup Poetry
      id: setup_poetry
      uses: snok/install-poetry@main
    - name: Add Poetry To Windows Path
      id: add_poetry_to_windows_path
      run: echo 'C:/Users/runneradmin/.local/bin' >> $GITHUB_PATH
      if: ${{ runner.os }} == 'Windows'
    - name: Install Python Dependencies
      id: install_python_dependencies
      run: poetry install
    - name: Setup Git
      id: setup_git
      run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
        && git config --global user.name "github-actions[bot]"
    - name: Setup Keyring
      id: setup_keyring
      run: poetry run pip install keyrings.alt && poetry run python -c "import keyring;
        from keyrings.alt.file import PlaintextKeyring; keyring.set_keyring(PlaintextKeyring());"
    - name: Run Pre Commit Hooks
      id: run_pre_commit_hooks
      run: poetry run pre-commit run --all-files --verbose
      env:
        REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
    - name: Commit Added Changes
      id: commit_added_changes
      run: 'git commit --no-verify -m ''[skip ci] CI/CD: Committing possible added
        changes (e.g.: pyproject.toml and poetry.lock)'''
    - name: Push Commits
      id: push_commits
      run: git push
    - name: Create And Push Tag
      id: create_and_push_tag
      run: git tag v$(poetry version -s) && git push origin v$(poetry version -s)
    - name: Download Artifacts
      id: download_artifacts
      uses: actions/download-artifact@main
      with:
        path: artifacts
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@develop
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@main
      with:
        tag: v$(poetry version -s)
        name: ${{ github.event.repository.name }} v$(poetry version -s)
        body: ${ steps.build_changelog.outputs.changelog }
        artifacts: artifacts*
