name: Create Release
'on':
  push:
    tags:
    - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: ${{ github.event.repository.name }}-${{ github.ref_name }}
        body: ${{ steps.build_changelog.outputs.changelog }}
