name: Release Workflow
'on':
  push:
    branches:
    - main
permissions:
  contents: write
run-name: 'Release Workflow: ${{ github.event.repository.name }} ${{ steps.version.outputs.version
  }}'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Extract Version from pyproject.toml
      id: version
      run: 'version=$(poetry version -s) && echo "Project version: $version" && echo
        "version=v$version" >> $GITHUB_OUTPUT'
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.x
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -
    - name: Install Dependencies
      run: poetry install
    - name: Run Hooks
      run: pre-commit run
    - name: Create and Push Tag
      run: git tag ${{ steps.version.outputs.version }} && git push origin ${{ steps.version.outputs.version
        }}
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.version.outputs.version }}
        name: ${{ github.event.repository.name }} ${{ steps.version.outputs.version
          }}
        body: ${{ steps.build_changelog.outputs.changelog }}
